---
# Source: wordpress-stack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-database
  labels:
    app: database
    env: dev
    id: c0911609
    stack: wordpress-stack
spec:
  selector:
    matchLabels:
      app: database
      env: dev
      id: c0911609
      stack: wordpress-stack
  replicas: 1
  template:
    metadata:
      labels:
        app: database
        env: dev
        id: c0911609
        stack: wordpress-stack
    spec:
      containers:
      - name: wp-database
        image: mariadb:10.6.4-focal
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: wp-database-configmap
              optional: false
          - secretRef:
              name: wp-database-secret
              optional: false
        ports:
        - containerPort: 3306
      #   volumeMounts:
      #   - name: wp-database-volume
      #     mountPath: /var/lib/mysql       # Path inside container
      # volumes:
      # - name: wp-database-volume
      #   hostPath:
      #     path: /var/lib/wp-data   # Path in host machine
