---
# Source: wordpress-stack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wp-database
  labels:
    app: database
    env: dev
    id: c0911609
    stack: wordpress-stack
spec:
  ports:
  - port: 3306            # the port on which the service is listening
    protocol: TCP
    targetPort: 3306      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: NodePort
  selector:
    app: database
    env: dev
    id: c0911609
    stack: wordpress-stack       # Pod label that service is using to select Pods
