# root tag name
wp:
  name: wpapp
  labels:
    id: c0911609
    app: wordpress
    env: dev
    stack: wordpress-stack
  image:
    # name of the repository from helm will pull the image
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 2
  configmap:
    ## KEY: "value"z
    APP_ENV: "dev"
    WORDPRESS_DB_HOST: "wp-database.wpdb.svc.cluster.local"
    WORDPRESS_DB_NAME: "wordpress"
    WORDPRESS_DB_USER: "wordpress"
  containerPorts:
      http: 80
